version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  web:
    build:
      context: ./WebFrontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

  mobile:
    build:
      context: ./MobileFrontend
    ports:
      - "8081:8081"
    volumes:
      - ./MobileFrontend:/app
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0

volumes:
  dev-db-data:
