version: "3.9"

services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  web:
    build:
      context: ./WebFrontend
    ports:
      - "3000:3000"
    volumes:
      - ./WebFrontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  mobile:
    build:
      context: ./MobileFrontend
    volumes:
      - ./MobileFrontend:/app
    command: ["npx", "react-native", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  dev-db-data:
  dev-static-data:
